<?php
    // Récupère les données des catégories et des produits depuis la variable $this->data
    $categories = $this->data["categories"];
    $products_filtered = $this->data["products-filtered"];
?>

<aside id="categories">
    <h2>Catégories</h2>
    <ul>
    <?php
        // Boucle à travers toutes les catégories et les affiche en tant qu'éléments de liste
        foreach($categories as $category)
        {
    ?> 
            <li><?=$category->getName();?></li>
        }
    </ul>
    <form method="POST" action="index.php?route=homepage-filtered">
         <input type="hidden" name="formName" value="getProductCategory"/>
         <label for="category_list">Quelle catégorie ?</label>
         <select name="category_list" id="category_list">
             <?php 
            foreach($categories as $category)
            {   
            ?>
                <option value="<?= $category['id']; ?>"> <?= $category['name']; ?> </option>
            <?php
            }
        ?>
        </select>
        <input type="submit" value="Submit"> 
     </form>

    
</aside>
<section id="products">
    <h2>Produits de la Categorie</h2> <!--dynamiser le nom de la category -->
    
    <?php
        // Affiche les 10 premiers produits dans une boucle
        for($i=0; $i<10; $i++)
        {
    ?> 
            <article class="card">
                <h3><?=$products_filtered[$i]->getName();?></h3>
                <img width="200" src="<?=$products_filtered[$i]->getUrlMedia();?>" alt="oui il en faudrait un">
                <p><?=$products_filtered[$i]->getDescription();?></p>
                <span><?=$products_filtered[$i]->getPrice();?>€</span>
            </article>
    <?php
        }
    ?>
</section>
