<?php
    $categories = $this->data["categories"];
    $products = $this->data["products"];
?>
<aside id="categories">
    <h2>Catégories</h2>
    <ul>
    <?php
        foreach($categories as $category)
        {?> 
            <li><?=$category->getName();?></li>
        <?php
        }
    ?>
    </ul>
</aside>
<section id="products">
    <h2>Produits</h2>
    <?php
        for($i=0; $i<10; $i++)
        {?> 
            <article class="card">
                <h3><?=$products[$i]->getName();?></h3>
                <p><?=$products[$i]->getDescription();?></p>
                <span><?=$products[$i]->getPrice();?></span>
            </article>
        <?php
        }
    ?>
</section>