<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://bootswatch.com/5/yeti/bootstrap.min.css">
</head>
<body>
    <?php
        if(isset($_SESSION["user"]))
        {
            require "views/user/connected/_header.phtml";
        }
        else
        {
            require "views/user/guest/_header.phtml";
        }
        
        require $this->template;

        if(isset($_SESSION["user"]))
        {
            require "views/user/connected/_footer.phtml";
        }
        else
        {
            require "views/user/guest/_footer.phtml";
        }
    ?>
</body>
</html>