<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <!--<script src="./assets/js/index.js"></script>-->
</head>

<body>
    <?php
    if (isset($_SESSION["user"])) {
        require "views/user/connected/_header.phtml";
    } else {
        require "views/user/guest/_header.phtml";
    } ?>
    <a href="index.php?route=cart">Mon panier</a>
    <main class="container">
        <?php 
        require $this->template; 
        ?>
    </main>
    

    <?php
    if (isset($_SESSION["user"])) {
        require "views/user/connected/_footer.phtml";
    } else {
        require "views/user/guest/_footer.phtml";
    }
    ?>
</body>

</html>