<section>
   <h2>Vos informations</h2>
   <form action="?route=account-edit">

   </form>
</section>
<section aria-labelledby="t-adresse">
   <h2 id="t-adresse">Vos adresses de livraison</h2>

   <h3>Ajouter une adresse</h3>
   <form action="?route=account-address-add" method="POST">
      <div>
         <label for="country">Pays</label>
         <input type="text" name="country" id="country" class="form-control">
         <label for="city">Ville</label>
         <input type="text" name="city" id="city" class="form-control">
         <label for="zip">Code postal</label>
         <input type="number" name="zip" id="zip" class="form-control">
      </div>
      <div>
         <label for="street">Adresse</label>
         <input type="text" name="street" id="street" class="form-control">
      </div>
      <div>
         <button type="submit">Confirmer</button>
      </div>
   </form>

   <form action="?route=account-address-edit">

   </form>
</section>
<section aria-labelledby="t-commandes">
   <h2 id="t-commandes">Vos dernières commandes</h2>
   <?php if (!$this->data['orders']) { ?>
      <p>Il n'y a rien par ici pour le moment...</p>
   <?php } else { ?>
      <table class="table">
         <thead>
            <tr>
               <th scope="col">#</th>
               <th scope="col">Date</th>
               <th scope="col">Quantité de produits</th>
               <th scope="col">Montant</th>
               <th scope="col">Status</th>
            </tr>
         </thead>
         <tbody>
            <?php foreach ($this->data['orders'] as $order) { ?>
               <tr>
                  <td scope="row"><?= $order->getId() ?></td>
                  <td><?= $order->getDate() ?></td>
                  <td><?= $order->getQuantity() ?></td>
                  <td><?= $order->getAmount() ?></td>
                  <td><?= $order->getStatus() ?></td>
               </tr>
            <?php } ?>
         </tbody>
      </table>
   <?php } ?>
</section>