<form action="index.php?route=register" method="POST">
    <label for="firstName">Prénom :</label>
    <input type="text" name="firstName" id="firstName">
    <label for="lastName"> Nom :</label>
    <input type="text" name="lastName" id="lastName">
    <label for="email">E-mail :</label>
    <input type="email" name="email" id="email">
    <label for="password">Mot de passe :</label>
    <input type="password" name="password" id="password">
    <label for="confirmPassword">Confirmer le mot de passe :</label>
    <input type="password" name="confirmPassword" id="confirmPassword">
    <input type="submit" value="Soumettre">
</form>