<form action="index.php?route=register" method="POST">
    <label for="firstName"></label>
    <input type="text" name="firstName" id="firstName">
    <label for="lastName"></label>
    <input type="text" name="lastName" id="lastName">
    <label for="email"></label>
    <input type="email" name="email" id="email">
    <label for="password"></label>
    <input type="password" name="password" id="password">
    <label for="confirmPassword"></label>
    <input type="password" name="confirmPassword" id="confirmPassword">
    <input type="submit" value="Soumettre">
</form>